import type { Metadata } from "next";
import SeoLanding from "../SeoLanding";

export const metadata: Metadata = {
  title: "WordPress-website traag? Zo wordt hij blijvend snel",
  description: "Trage WordPress-site? Cache-plugins zijn lapmiddelen. Wij zetten je site om naar een versie die altijd direct laadt — beter voor bezoekers én Google.",
  alternates: { canonical: "/wordpress-website-traag" },
};

export default function Pagina() {
  return <SeoLanding data={{"slug": "wordpress-website-traag", "label": "Trage WordPress-site", "titel": "Is je WordPress-website traag? Dit is de blijvende oplossing", "intro": "Cache-plugins, image-optimizers, snellere hosting: het zijn allemaal lapmiddelen voor hetzelfde probleem — WordPress moet elke pagina opnieuw ópbouwen als iemand hem opvraagt. Wij draaien het om: je pagina's staan kant-en-klaar op het netwerk van Cloudflare, wereldwijd, en laden daardoor vrijwel direct. Zonder één plugin.", "blokken": [{"kop": "Waarom je WordPress-site traag is", "tekst": "Bij elk bezoek start WordPress een keten op: database bevragen, thema laden, tientallen plugins draaien, pagina samenstellen. Hoe meer plugins en hoe drukker je hosting, hoe trager het wordt. Cache-plugins verzachten dat, maar de machine blijft de zwakke schakel — en na elke update kan het weer anders zijn."}, {"kop": "Waarom snelheid direct geld waard is", "tekst": "Bezoekers haken af bij trage sites — elke seconde laadtijd kost bewezen conversie. En Google gebruikt snelheid (Core Web Vitals) als rankingfactor: een trage site wordt structureel lager getoond dan een snelle concurrent met dezelfde content."}, {"kop": "Onze aanpak: de machine weghalen", "tekst": "We zetten je site om naar kant-en-klare pagina's die direct vanaf het Cloudflare-netwerk geserveerd worden — hetzelfde design, dezelfde content, dezelfde URL's. Er is geen database of plugin meer die kán vertragen. Typische uitkomst: laadtijden onder de seconde en groene Core Web Vitals."}, {"kop": "Sneller én zorgelozer", "tekst": "De snelheidswinst is meteen ook het einde van je onderhoud: geen updates, niets te hacken, geen hostingkosten. Aanpassen doe je via chat, met een voorbeeld vooraf en no cure, no pay op de overstap."}], "faq": [{"vraag": "Hoeveel sneller wordt mijn site echt?", "antwoord": "Statische pagina's vanaf een wereldwijd netwerk laden typisch in enkele honderden milliseconden — waar een gemiddelde WordPress-site seconden nodig heeft. Je mag ons aan de meting houden: we vergelijken de scores van oud en nieuw bij de oplevering."}, {"vraag": "Helpt dit ook voor mijn positie in Google?", "antwoord": "Ja, dubbel: snelheid is een rankingfactor, en we nemen tegelijk al je SEO (URL's, titels, omschrijvingen) 1-op-1 over zodat je niets verliest van wat je hebt opgebouwd."}, {"vraag": "Kan ik niet gewoon een cache-plugin nemen?", "antwoord": "Dat kan, en het helpt tijdelijk. Maar het voegt wéér een plugin toe aan de machine die het probleem veroorzaakt. Wij lossen de oorzaak op in plaats van het symptoom."}, {"vraag": "Wat kost het?", "antwoord": "De overstap kost eenmalig €250–€750 (no cure, no pay), daarna €5–€20 per maand voor de AI-koppeling. Vaak minder dan wat je nu aan hosting en plugins kwijt bent."}]}} />;
}
