/**
 * Het vaste Worker-script dat een klantsite uit R2 serveert. Voor élke site
 * identiek; alleen de bindings verschillen (SITES = de bucket, PREFIX = het
 * voorvoegsel van deze site). Het script verandert dus niet bij een wijziging
 * van de site — daarom is een wijziging direct overal zichtbaar.
 *
 * Wat het overneemt van de vroegere Cloudflare-assets-instellingen:
 *  - /pad → /pad/ (307) als pad/index.html bestaat, en /pad/ → index.html
 *  - /pad → pad.html als dat bestaat
 *  - 404.html met status 404
 *  - _redirects (301's; houdt oude adressen en Google-posities intact)
 *  - _headers (beveiligingsheaders uit de site zelf)
 *  - noindex op workers.dev-adressen, www → kaal domein (301)
 *  - ETag/If-None-Match (304), Range-verzoeken (video seeken), mime-types
 *
 * Verhoog R2_SCRIPT_VERSIE bij elke wijziging aan dit script: de deploy
 * publiceert het script dan opnieuw voor elke site die aan de beurt is.
 */
export const R2_SCRIPT_VERSIE = "4";

export const R2_WORKER_SCRIPT = [
  'const HTML = "text/html; charset=utf-8";',
  "const MIME = {",
  '  html: HTML, htm: HTML, css: "text/css; charset=utf-8", js: "text/javascript; charset=utf-8",',
  '  mjs: "text/javascript; charset=utf-8", json: "application/json; charset=utf-8", xml: "application/xml; charset=utf-8",',
  '  txt: "text/plain; charset=utf-8", md: "text/markdown; charset=utf-8", svg: "image/svg+xml", png: "image/png",',
  '  jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp", gif: "image/gif", ico: "image/x-icon", avif: "image/avif",',
  '  woff2: "font/woff2", woff: "font/woff", ttf: "font/ttf", otf: "font/otf", mp4: "video/mp4", webm: "video/webm",',
  '  mp3: "audio/mpeg", ogg: "audio/ogg", wav: "audio/wav", pdf: "application/pdf", zip: "application/zip",',
  '  wasm: "application/wasm", webmanifest: "application/manifest+json", vtt: "text/vtt; charset=utf-8",',
  "};",
  "let regelsCache = null;",
  "",
  "function mimeVoor(pad) {",
  '  const ext = (pad.split(".").pop() || "").toLowerCase();',
  '  return MIME[ext] || "application/octet-stream";',
  "}",
  "",
  "function patroon(p) {",
  '  const esc = p.replace(/[.+?^${}()|[\\]\\\\]/g, "\\\\$&").replace(/\\*/g, ".*").replace(/:[A-Za-z0-9_]+/g, "[^/]+");',
  '  return new RegExp("^" + esc + "$");',
  "}",
  "",
  "async function laadRegels(env) {",
  "  const nu = Date.now();",
  "  if (regelsCache && nu - regelsCache.tijd < 30000) return regelsCache;",
  '  const [r, h] = await Promise.all([env.SITES.get(env.PREFIX + "/_redirects"), env.SITES.get(env.PREFIX + "/_headers")]);',
  "  const redirects = {};",
  "  if (r) {",
  '    for (const regel of (await r.text()).split("\\n")) {',
  "      const schoon = regel.trim();",
  '      if (!schoon || schoon.startsWith("#")) continue;',
  "      const [van, naar, code] = schoon.split(/\\s+/);",
  '      if (!van || !naar || van.includes("*") || van.includes(":")) continue;',
  '      redirects[van.replace(/\\/+$/, "") || "/"] = { naar, code: Number(code) || 301 };',
  "    }",
  "  }",
  "  const headers = [];",
  "  if (h) {",
  "    let huidig = null;",
  '    for (const regel of (await h.text()).split("\\n")) {',
  '      if (!regel.trim() || regel.trim().startsWith("#")) continue;',
  "      if (!/^\\s/.test(regel)) { huidig = { test: patroon(regel.trim()), kop: [] }; headers.push(huidig); continue; }",
  '      const i = regel.indexOf(":");',
  "      if (huidig && i > 0) huidig.kop.push([regel.slice(0, i).trim(), regel.slice(i + 1).trim()]);",
  "    }",
  "  }",
  "  regelsCache = { tijd: nu, redirects, headers };",
  "  return regelsCache;",
  "}",
  "",
  "async function haal(env, key, request, voorwaardelijk) {",
  "  try {",
  "    return await env.SITES.get(key, voorwaardelijk ? { onlyIf: request.headers, range: request.headers } : undefined);",
  "  } catch (e) {",
  "    return null;",
  "  }",
  "}",
  "",
  "export default {",
  "  async fetch(request, env) {",
  "    const url = new URL(request.url);",
  "    // www → kaal domein (één canoniek adres, geen dubbele inhoud voor Google)",
  '    if (url.hostname.startsWith("www.")) {',
  "      url.hostname = url.hostname.slice(4);",
  "      return Response.redirect(url.toString(), 301);",
  "    }",
  '    if (request.method !== "GET" && request.method !== "HEAD") {',
  '      return new Response("Methode niet toegestaan", { status: 405, headers: { allow: "GET, HEAD" } });',
  "    }",
  "    let pad;",
  "    try { pad = decodeURIComponent(url.pathname); } catch (e) { pad = url.pathname; }",
  '    if (pad.includes("..") || /(^|\\/)\\.[^/]*$/.test(pad)) {',
  '      return new Response("Pagina niet gevonden", { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });',
  "    }",
  "    const regels = await laadRegels(env);",
  '    const doel = regels.redirects[pad.replace(/\\/+$/, "") || "/"];',
  "    if (doel) return Response.redirect(new URL(doel.naar, url.origin).toString(), doel.code);",
  "",
  '    const prefix = env.PREFIX + "/";',
  "    const rel = pad.slice(1);",
  '    const laatste = pad.split("/").pop();',
  "    let key;",
  '    if (pad.endsWith("/")) key = prefix + rel + "index.html";',
  '    else if (laatste.includes(".")) key = prefix + rel;',
  "    else {",
  '      if (await env.SITES.head(prefix + rel + "/index.html")) {',
  '        url.pathname = pad + "/";',
  "        return Response.redirect(url.toString(), 307);",
  "      }",
  '      key = prefix + rel + ".html";',
  "    }",
  "    let status = 200;",
  "    let obj = await haal(env, key, request, true);",
  "    if (!obj) {",
  "      status = 404;",
  '      key = prefix + "404.html";',
  "      obj = await haal(env, key, request, false);",
  '      if (!obj) return new Response("Pagina niet gevonden", { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });',
  "    }",
  "",
  "    const kop = new Headers();",
  '    kop.set("content-type", mimeVoor(key));',
  '    kop.set("etag", obj.httpEtag);',
  '    kop.set("accept-ranges", "bytes");',
  "    // Alles wat via het portaal kan veranderen (pagina's, css, js, beelden) altijd",
  "    // laten controleren: een 304 is goedkoop en de klant ziet nooit een oude versie.",
  "    // Alleen video en lettertypen (groot, veranderen zelden) mag de browser bewaren.",
  '    const bewaarbaar = /\\.(mp4|webm|mp3|ogg|wav|woff2?|ttf|otf)$/i.test(key) && status === 200;',
  '    kop.set("cache-control", bewaarbaar ? "public, max-age=3600, must-revalidate" : "no-cache");',
  "    for (const h of regels.headers) if (h.test.test(pad)) for (const [n, w] of h.kop) kop.set(n, w);",
  '    if (url.hostname.endsWith(".workers.dev")) kop.set("x-robots-tag", "noindex, nofollow");',
  "",
  "    // Voorwaarde niet gehaald (If-None-Match): R2 geeft dan het object zonder body terug",
  '    if (status === 200 && obj.body === undefined) {',
  "      return new Response(null, { status: 304, headers: kop });",
  "    }",
  '    if (status === 200 && obj.range && request.headers.has("range")) {',
  '      const start = "offset" in obj.range ? obj.range.offset : 0;',
  '      const lengte = "length" in obj.range ? obj.range.length : obj.size - start;',
  '      if ("suffix" in obj.range) {',
  "        const s = obj.size - obj.range.suffix;",
  '        kop.set("content-range", "bytes " + s + "-" + (obj.size - 1) + "/" + obj.size);',
  "      } else {",
  '        kop.set("content-range", "bytes " + start + "-" + (start + lengte - 1) + "/" + obj.size);',
  "      }",
  '      kop.set("content-length", String("suffix" in obj.range ? obj.range.suffix : lengte));',
  '      return new Response(request.method === "HEAD" ? null : obj.body, { status: 206, headers: kop });',
  "    }",
  '    kop.set("content-length", String(obj.size));',
  '    return new Response(request.method === "HEAD" ? null : obj.body, { status, headers: kop });',
  "  },",
  "};",
  "",
].join("\n");
