import type { Metadata } from "next";
import SeoLanding from "../SeoLanding";

export const metadata: Metadata = {
  title: "Een website zonder onderhoud — bestaat dat?",
  description: "Ja: een onderhoudsvrije website zonder updates, plugins of hostinggedoe. Wij zetten je huidige site over; aanpassen doe je daarna via chat. Vanaf €250.",
  alternates: { canonical: "/website-zonder-onderhoud" },
};

export default function Pagina() {
  return <SeoLanding data={{"slug": "website-zonder-onderhoud", "label": "Website zonder onderhoud", "titel": "Een website zonder onderhoud — het bestaat echt", "intro": "De meeste websites zijn nooit af: er is altijd wel een update, een kapotte plugin of een hostingmail die aandacht vraagt. Dat komt door hoe ze gebouwd zijn — als draaiende machines. WordSwap zet je site om naar een vorm die gewoon áf is: platte, snelle web-bestanden waar niets aan kapot kan. Onderhoud bestaat simpelweg niet meer.", "blokken": [{"kop": "Waarom een gewone website onderhoud vraagt", "tekst": "Een WordPress-site is een programma dat continu draait: een database, PHP, tientallen plugins. Elk onderdeel moet bijgewerkt blijven, anders ontstaan er beveiligingsgaten — en updates kunnen zelf ook weer dingen breken. Vandaar back-ups, onderhoudscontracten en toch af en toe een gehackte site."}, {"kop": "Hoe een onderhoudsvrije website werkt", "tekst": "Wij bevriezen je site tot z'n essentie: de pagina's zelf, zonder draaiende machine eromheen. Die bestanden staan op het wereldwijde netwerk van Cloudflare — sneller dan welke WordPress-hosting ook, en er valt niets te updaten of te hacken. Je contactformulier en statistieken blijven gewoon werken."}, {"kop": "Maar dan kan ik toch niets meer wijzigen?", "tekst": "Juist wel — makkelijker dan ooit. Je typt in de chat wat er anders moet (\"zet de zomeropeningstijden erop\", \"voeg een pagina toe over dakisolatie\") en de AI voert het uit. Je ziet elke wijziging eerst als voorbeeld en keurt hem zelf goed. Geen beheerschermen, geen handleidingen."}, {"kop": "Wat het scheelt per maand", "tekst": "Geen hosting (€10–25), geen premium plugins (€5–30), geen onderhoudscontract (€30+) en geen facturen van je webbouwer voor kleine aanpassingen. Daarvoor in de plaats: €5–€20 per maand voor de AI-koppeling, afgestemd op je gebruik."}], "faq": [{"vraag": "Is een statische website niet ouderwets?", "antwoord": "Integendeel — het is hoe de snelste sites van dit moment gebouwd zijn. Voor bezoekers en Google is het verschil: sneller laden, betere beveiliging, hogere scores."}, {"vraag": "Wat gebeurt er als er tóch iets misgaat?", "antwoord": "We bewaren de complete geschiedenis van je site: elke eerdere versie kan met één handeling teruggezet worden. Er kan niets definitief stuk."}, {"vraag": "Werkt mijn contactformulier nog?", "antwoord": "Ja, en beter: inzendingen komen in je eigen portaal, worden doorgemaild naar je e-mailadres en zijn standaard beschermd tegen spam-robots."}, {"vraag": "Voor welke sites werkt dit niet?", "antwoord": "Webshops, ledenportalen en boekingssystemen met live agenda hebben een draaiende machine nodig en passen hier niet in. Vrijwel elke andere bedrijfssite wel."}]}} />;
}
